 export type Action =
 
  | "create_client"
  | "view_client"
  | "edit_client"
  | "delete_client"
  | "create_prestamo"
  | "view_prestamo"
  | "edit_prestamo"
  | "delete_prestamo"
  | "manage_employees"
  | "view_reports"
  | "create_loan"
  | "view_loan"
  | "edit_loan"
  | "delete_loan"
  | "create_payment"
  | "view_payment"
  | "edit_payment"
  | "delete_payment"
   | "pay_payment"
   | "create_notification"
  | "view_notification"
  | "edit_notification"
  | "delete_notification"
   | "mark_read_notification"