 export type Action =
    |"lender:create"
  | "client:create"
  | "view_client"
  | "edit_client"
  | "delete_client"
  | "create:loan"
  | "view_prestamo"
  | "edit_prestamo"
  | "delete_prestamo"
  | "manage_employees"
  | "view_reports"
  | "loan:create"
  | "loan:delete"
  | "view_loan"
  | "edit_loan"
  | "delete_loan"
  | "create_payment"
  | "view_payment"
  | "payment:edit"
  | "delete_payment"
  | "payment:pay"
   | "pay_payment"
   | "create_notification"
  | "view_notification"
  | "edit_notification"
  | "delete_notification"
   | "mark_read_notification"